FROM --platform=linux/amd64 python:3.9

RUN apt-get update

# RUN pip install virtualenv
# ENV VIRTUAL_ENV=/venv
# RUN virtualenv venv -p python3
# ENV PATH="VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip

# COPY main.py bot.py ./handlers/azure_moderation.py ./handlers/handle_moderation.py ./handlers/chat_speed.py ./handlers/get_channels.py ./handlers/violations_database_handler.py .env requirements.txt ./

COPY main.py bot.py .env requirements.txt ./

COPY ./handlers ./handlers

RUN pip install -r requirements.txt

EXPOSE 8080

WORKDIR .
# CMD ["source venv/bin/activate"]
CMD ["python3", "-u" ,"main.py"]