FROM --platform=linux/amd64 python:3.9

RUN apt-get update

# RUN pip install virtualenv
# ENV VIRTUAL_ENV=/venv
# RUN virtualenv venv -p python3
# ENV PATH="VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip

# RUN pip install -r requirements.txt

COPY main.py bot.py responses.py gcp_moderation.py azure_moderation.py handle_moderation.py commands.py .env requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 8080

WORKDIR .
# CMD ["source venv/bin/activate"]
CMD ["python3", "-u" ,"main.py"]